# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-21 11:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leap_user1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='department',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='role',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
