# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-21 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leap_user1', '0004_remove_fields_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='fields',
            name='Active',
            field=models.CharField(choices=[(1, b'Yes'), (0, b'No')], default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fields',
            name='department',
            field=models.CharField(blank=True, choices=[(1L, 'Engineering'), (2L, 'operations')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='fields',
            name='role',
            field=models.CharField(blank=True, choices=[(1L, 'IC'), (2L, 'Sr IC')], max_length=200, null=True),
        ),
    ]
